import { useEffect,useMemo,useState,type ReactNode } from 'react';
import { Activity,ArrowLeft,ArrowRight,CalendarDays,CheckCircle2,ChevronLeft,ChevronRight,Download,Grid3X3,Landmark,MapPin,Save,Search,Settings,Sparkles,Star,Store,User,Users } from 'lucide-react';
import type { ProductPage } from './pageLibrary';
import './functional-screens.css';

type CrowdLevel='low'|'moderate'|'high'|'critical';
type Props={page:ProductPage;pages:ProductPage[];onBack:()=>void;onOpen:(page:ProductPage)=>void;crowdLevel:string;crowdLabel:string;crowdWait:string;onCrowdChange?:(level:CrowdLevel)=>void|Promise<void>;onResetDemo?:()=>void|Promise<void>;onOpenCore?:(target:'home'|'map'|'plan'|'bookings'|'profile')=>void};
type LocalState={notes:string;enabled:boolean;saved:boolean;items:string[]};
const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function useLocal(page:ProductPage){const key=`yatralink:vercel:${slug(page.role)}:${slug(page.module)}:${slug(page.title)}`;const [state,setState]=useState<LocalState>(()=>{try{return JSON.parse(localStorage.getItem(key)||'') as LocalState}catch{return{notes:'',enabled:true,saved:false,items:[]}}});useEffect(()=>{localStorage.setItem(key,JSON.stringify(state))},[key,state]);return[state,setState] as const}
const icon=(module:string):ReactNode=>module.includes('Crowd')?<Activity/>:module.includes('Journey')?<Sparkles/>:module.includes('Booking')?<CalendarDays/>:module.includes('Experience')?<Landmark/>:module.includes('Account')?<User/>:<Grid3X3/>;
function RouteBar({page,pages,onBack,onOpen}:{page:ProductPage;pages:ProductPage[];onBack:()=>void;onOpen:(p:ProductPage)=>void}){const sib=pages.filter(p=>p.role===page.role&&p.module===page.module);const i=sib.findIndex(p=>p.id===page.id);return <header className='fs-routebar'><button onClick={onBack}><ArrowLeft/> All screens</button><div><span>{page.role} · {page.module}</span><b>{i+1} / {sib.length}</b></div><div><button disabled={i<=0} onClick={()=>i>0&&onOpen(sib[i-1])}><ChevronLeft/> Previous</button><button disabled={i>=sib.length-1} onClick={()=>i<sib.length-1&&onOpen(sib[i+1])}>Next <ChevronRight/></button></div></header>}
function CoreAction({page,onOpenCore}:{page:ProductPage;onOpenCore?:Props['onOpenCore']}){const t=page.title.toLowerCase();if(t.includes('ai trip')||page.module==='Journey')return <button className='fs-primary' onClick={()=>onOpenCore?.('plan')}><Sparkles/>Open working Journey</button>;if(page.module==='Crowd Intelligence')return <button className='fs-primary' onClick={()=>onOpenCore?.('map')}><MapPin/>Open live map</button>;if(page.module==='Booking')return <button className='fs-primary' onClick={()=>onOpenCore?.('bookings')}><CalendarDays/>Open bookings</button>;if(page.module==='Account & Support')return <button className='fs-primary' onClick={()=>onOpenCore?.('profile')}><User/>Open profile</button>;return <button className='fs-primary' onClick={()=>onOpenCore?.('home')}><ArrowRight/>Open traveler app</button>}
function ModulePreview({page,crowdLabel,crowdWait,state,setState,onOpenCore}:{page:ProductPage;crowdLabel:string;crowdWait:string;state:LocalState;setState:React.Dispatch<React.SetStateAction<LocalState>>;onOpenCore?:Props['onOpenCore']}){const rows=useMemo(()=>page.module==='Experiences'?['Traditional Woodcarving Workshop','Newari Lunch Experience','Living Heritage Walk']:page.module==='Crowd Intelligence'?['Patan Durbar Square','Golden Temple','Mangal Bazaar']:['Primary workflow','Saved prototype state','Next recommended action'],[page.module]);const save=()=>setState(s=>({...s,saved:true}));return <div className='fs-screen-body'><section className='fs-hero'><span>{icon(page.module)}</span><div><small>{page.role.toUpperCase()} · {page.module.toUpperCase()}</small><h1>{page.title}</h1><p>{page.description}</p></div></section>{page.module==='Crowd Intelligence'&&<div className='fs-crowd-preview'><div><MapPin/><strong>Patan Durbar Square</strong><b>{crowdLabel}</b><small>{crowdWait}</small></div><div className='fs-fake-map'><i/><i/><i/><span/></div></div>}{page.module==='Rewards & Impact'&&<div className='fs-kpis'><article><b>650</b><small>Heritage Points</small></article><article><b>3</b><small>Local actions</small></article></div>}<section className='fs-panel'><div className='fs-panel-head'><div><h2>Interactive prototype workflow</h2><p>This route preserves the complete product architecture while the core production-demo workflows use the shared Supabase backend.</p></div><Search/></div><div className='fs-simple-list'>{rows.map((r,i)=><button key={r} onClick={()=>setState(s=>({...s,items:s.items.includes(r)?s.items.filter(x=>x!==r):[...s.items,r]}))}><span>{i===0?<Store/>:i===1?<Star/>:<CheckCircle2/>}</span><div><strong>{r}</strong><small>{state.items.includes(r)?'Selected':'Tap to select'}</small></div><CheckCircle2 className={state.items.includes(r)?'on':''}/></button>)}</div></section><section className='fs-panel'><h2>Page state</h2><label className='fs-note-field'>Notes<textarea value={state.notes} onChange={e=>setState(s=>({...s,notes:e.target.value,saved:false}))} placeholder='Add prototype notes…'/></label><label className='fs-toggle-line'><span><strong>Enabled</strong><small>Demonstrates persistent screen state</small></span><button className={state.enabled?'on':''} onClick={()=>setState(s=>({...s,enabled:!s.enabled,saved:false}))}><i/></button></label><div className='fs-actions'><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({page:page.title,state},null,2)],{type:'application/json'}));a.download=`${slug(page.title)}.json`;a.click()}}><Download/>Export</button><button className='fs-primary' onClick={save}><Save/>{state.saved?'Saved':'Save state'}</button></div></section><CoreAction page={page} onOpenCore={onOpenCore}/></div>}
export default function ProductScreenRenderer({page,pages,onBack,onOpen,crowdLabel,crowdWait,onOpenCore}:Props){const [state,setState]=useLocal(page);const traveler=page.role==='Traveler';return <div className='fs-route'><RouteBar page={page} pages={pages} onBack={onBack} onOpen={onOpen}/>{traveler?<div className='fs-mobile-stage'><div className='fs-phone'><header className='fs-phone-head'><button onClick={onBack}><ArrowLeft/></button><div><strong>{page.title}</strong><small>{page.module}</small></div>{icon(page.module)}</header><main><ModulePreview page={page} crowdLabel={crowdLabel} crowdWait={crowdWait} state={state} setState={setState} onOpenCore={onOpenCore}/></main><nav className='fs-phone-nav'>{[['Explore','Home'],['Crowd Intelligence','Map'],['Journey','Journey'],['Booking','Bookings'],['Account & Support','Profile']].map(([m,l])=><button key={m} className={page.module===m?'active':''} onClick={()=>{const p=pages.find(x=>x.role==='Traveler'&&x.module===m);if(p)onOpen(p)}}>{icon(m)}<span>{l}</span></button>)}</nav></div></div>:<div className='fs-desktop'><aside><div className='fs-brand'><span>{icon(page.module)}</span><div><strong>YatraLink</strong><small>{page.role}</small></div></div><nav>{Array.from(new Set(pages.filter(p=>p.role===page.role).map(p=>p.module))).map(m=><button key={m} className={m===page.module?'active':''} onClick={()=>{const p=pages.find(x=>x.role===page.role&&x.module===m);if(p)onOpen(p)}}>{icon(m)}<span>{m}</span></button>)}</nav></aside><main><ModulePreview page={page} crowdLabel={crowdLabel} crowdWait={crowdWait} state={state} setState={setState} onOpenCore={onOpenCore}/></main></div>}</div>}
